//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WisT.DemoWeb.Persistence.DataEntities
{

    public partial class UserImage
    {
        public int ImageId { get; set; }
        public int Id { get; set; }
        public byte[] Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
